version: "2"

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - /Users/vkn/damma:/var/lib/postgresql/db-data

  app:
    build: .
    env_file: .env
    environment:
      RAILS_ENV: production
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
